### ISSUE TITLE
Update portfolio

### ISSUE THREAD

**Issue by lilahmedina** [lilahmedina/delilah.github.io#1]
### Tasks:

- [ ]  Pick the top 3 outstanding projects. 
- [x] Update the favicon 
- [x] Add illustrations
- [ ] Add resume
- [x] dark/light mode theme
